language: node_js
node_js:
- "8"
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - master
env:
  global:
  - GH_USER_NAME: rghorbani
  - GH_PROJECT_NAME: react-native-common
  - GH_FULL_NAME: Reza Ghorbani Farid
  - GH_EMAIL: r.ghorbani.f@gmail.com
  - SITE_URL: https://rghorbani.ir
  - GH_REF: github.com/rghorbani/react-native-common/
  - secure: VuNN+STvL24FGlqFlkfyVPISbEKgmwLUDoDVj7DT/0N0JHsFv3+EY7KCnDpOFkWXbuznwVBH8jZYJlNgZFxx+FlcE9lV+/DFz4Ibe651Tu5bMTGTu5F+f/A7zaMbwXWYLFV+3t1K4+H2VcClkkGLC5J7kEtToQCVNDsPUNVHBSUJ65vX7TuJyir3dwPNunXMaB5VH4WLyfkJwDYG05/Y3Zcql8I0gweZf/poyCE9EcA8mwAQD+Oy9p6dogpGJei6Okmks3i7A0W2bg4k14MxsJulsGgtfjG9xDnaRIA4sPmK6S6qfu9lrN3iRU82mGigsj/7jOkQ/lP0I//lorR8oCSmyPhmFBMMjUQH+kxHml59zsA+q2GKWaQCz4OUYvRJsD+j7XihIMmX4R3ms+l2kOBvxw0RzTni51CCxz5lOzLw3tjKYY7dn6I2xDicgTSCqSiFtu1DQavHZB+ekNuew/oJUhubbsGPWo4sZSk54FbO3mMauRgiuBqDjMaOuDPsc1qiWSKMh3VZYkdRs/txEbkl11sXQSyHUv8rG7Nv0/0/sOU9KxHkunecNY6Ynat8ovq2A1j3hxdAnq2zJc6sBTe6Lt1M0LioN48VGByBxxSHTcUDVAF1iYVzPW5kyhRxy2mWhl4s2xpvn6EYln4X8dG5QDL9M3yIdItHPBiWLNE=
install:
- yarn
